### ISSUE TITLE
Noob in need of help

### ISSUE THREAD

**Issue by pralph8974** [den1s/quagga_zabbix_bgp_mon#5]
Good Morning,
I am new to Zabbix and was hoping that you would have a guide to follow for setting this up. I am hoping to be able to monitor my routers BGP sessions with this. Would this work?

**Comment by den1s** [comment]
Hello!
What software your using for BGP?

**Comment by pralph8974** [comment]
Bgp is running on my Cisco routers

**Comment by den1s** [comment]
That zabbix template for software routers like quagga or FRR.

You can not use for cisco.

Maybe [that link](https://share.zabbix.com/network_devices/cisco/template-cisco-bgp-snmp) can help you.
